name: CI

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

#       - name: Fastlane Action
#         run: maierj/fastlane-action@v2.0.0
        
      - name: Run tests
        uses: ./GithubActions && bundle exec fastlane tests
