name: CI 

on:
  push: 
    branches: [main]
    
jobs: 
  tests: 
    runs-on: macOS-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Run tests
        uses: bundle exec fastlane test
    
