name: CI

on:
  push:
    branches: [main]

jobs:
  tests:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2.3.4

      - name: Install fastlane
        run: |
          gem install fastlane -NV

      - name: Run tests
        uses: ./GithubActions/
        run: bundle exec fastlane tests
