name: Testflight

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testflight:
    runs-on: macOS-latest

    steps:
      - uses: actions/checkout@v2.3.4

      # - name: Install Homebrew
      #   run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1.64.1
        with:
          ruby-version: 2.7.2

      - name: Install Fastlane
        run: sudo gem install fastlane

      - name: Install Coacopods
        run: sudo gem install cocoapods

      - name: Run Coacopods
        run: |
          cd GithubActions/
          pwd
          pod install

      - name: Update bundle
        run: |
          cd GithubActions && bundle install

      - name: Run Testflight lane
        env:
          APP_NAME: "${{ secrets.APP_NAME }}"
        run: bundle exec fastlane test
