name: Testflight

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  testflight:
    runs-on: macos-latest

    steps:
      - uses: actions/checkout@v2.3.4
      - uses: ruby/setup-ruby@v1.64.1
        with:
          ruby-version: 2.7.2

      - name: Install Coacopods
        run: sudo gem install cocoapods

      - name: Run Coacopods
        run: |
          cd GithubActions
          pod install

      - name: Install Fastlane
        run: |
          sudo gem install fastlane
          export LC_ALL=en_US.UTF-8
          export LANG=en_US.UTF-8

      - name: Update bundle
        run: |
          cd GithubActions          
          sudo bundle install
          sudo bundle update fastlane

      - name: Run Testflight lane
        env:
          APP_NAME: "${{ secrets.APP_NAME }}"
        run: |
          cd GithubActions
          bundle exec fastlane test

# cd GithubActions
# sudo gem install cocoapods
# pod install
# sudo gem install fastlane
# export LC_ALL=en_US.UTF-8
# export LANG=en_US.UTF-8
# sudo bundle install
# sudo bundle update fastlane
# bundle exec fastlane test
