
name: Testflight

on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs: 
  testflight: 
    runs-on: macOS-latest
    
    steps: 
      - uses: actions/checkout@v2.3.4
        
      - name: Install Homebrew
        run: /bin/bash -c "$(curl -fsSL https://raw.githubusercontent.com/Homebrew/install/HEAD/install.sh)"
        
      - name: Install Fastlane
        run: brew install fastlane
      
      - name: Install Coacopods
        run: sudo gem install cocoapods
        
      - name: Run Coacopods
        run: pod install 
        
      - name: Update bundle
        run: bundle update fastlane
      
      - name: Run Testflight lane
        run: bundle exec fastlane test
      
  
